### ISSUE TITLE
Feature: User can log a workout

### ISSUE THREAD

**Issue by btoomepuu** [btoomepuu/ajax-project#1]
## ⚙️ Feature

> ##### Users can add a workout entry.

## 📐 Functionality

> ##### User will be able to add workout, including sets and reps for different exercises. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

!
![Screen Shot 2022-08-01 at 6 14 04 PM](https://user-images.githubusercontent.com/59620542/182257281-3b390c47-a910-4dab-89e7-47e3dd839e43.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create calendar user can add entries to 
- [ ] Add a form for creating a new workout
- [ ] Add more form lines if user indicates
- [x] Listen for submit on events of form
    - [x] Put form's input values in a new object
    - [x] Add workout id
    - [ ] Update workout id for next workout
    - [x] Prepend the new object to the entries in the data model
    - [ ] Reset form
- [x] Verify that new entries are saved to local storage along with the rest of the data model on page reload.
- [x] Verify that each new entry receives a workout id
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
